steps:

- id: "RUN docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "RUN golang application test"
  name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=/go/bin/main']
  args: ['test']

- id: "RUN golang application"
  name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=/go/bin/main']
  args: ['run', 'main.go']